print ( "first" + "second" )
print ( "hello world" .upper())
print ( "HELLO WORLD" .lower())
print ( "hello world" .capitalize())
print ( len ( "hello world" ))
print ( "hello world" . __len__ ())
print ( "Hello world" .replace( "world" , "World" ))
print ( "hello world" .find( "world" ))
s = '-'
seq = ( "a" , "b" , "c" )
print (s.join(seq))
print ( "test " + "3" + " test" )
print ( "test " + str ( 3 ) + " test" )
print ( 3 * 4 )
print ( 3 + 4 )
x = 4.0
y = 3
print (x-y)
print (x*y)
print (x+y)
print (x/y)
print ( int ( 3.5 ))
print ( int (- 3.5 ))
print ( "496" )
print ( 3e2 )
print ( float ( 8 ))
print ( float ( "496.5" ))
print ( float ( "inf" ))
print ( float ( "-inf" ))
print ( 3.0 + 1 )
print ( True )
print ( False )
print ( bool ( 0 ))
print ( bool (- 1 ))
print ( bool ( 0.0 ))
print ( bool (x))
print ( bool (x+y))
print ( bool ( 0.207 ))
print ( bool (- 1.117 ))
print ( bool ([]))
print ( bool ([ 1 , 5 , 9 ]))
print ( bool ( "" ))
print ( bool ( "Spam" ))
print ( bool ( "False" ))
print ( bool ( False ))
z = 2 + 3j
print (z.real)
print (z.imag)
print ( abs ( 3 + 4j ))
print (z.conjugate())
print ( pow ( 3 + 4j , 2 ))
print ( complex ( 2 , 3 ))
